language: r
r: bioc-devel
sudo: required
cache: packages
r_binary_packages:
  - lme4
  - multcomp
  - dplyr
  - tidyr
  - reshape2
  - magrittr
  - knitr
  - rmarkdown
  - mime
  - curl
  - openssl
  - R6
  - httr
  - memoise
  - whisker
  - digest
  - rstudioapi
  - jsonlite
  - git2r
  - withr
  - devtools
  - colorspace
  - shape
  - rjson
  - RColorBrewer
  - abind
  - carData
  - sp
  - maptools
  - pbkrtest
  - MatrixModels
  - SparseM
  - quantreg
  - data.table
  - forcats
  - hms
  - readr
  - haven
  - rematch
  - cellranger
  - readxl
  - gtools
  - plotrix
  - dichromat
  - labeling
  - munsell
  - viridisLite
  - scales
  - gtable
  - lazyeval
  - ggplot2
  - httpuv
  - sourcetools
  - xtable
  - shiny
  - crosstalk
  - htmlwidgets
  - DT
  - corpcor
  - matrixStats
  - DEoptimR
  - robustbase
  - RUnit
  - XML
  - igraph
  - gridExtra
  - nnls
  - hexbin
  - plotly
  - shinyBS
  - shinydashboard
  - shinyjs
  - futile.options
  - formatR
  - lambda.r
  - futile.logger
  - snow
  - bitops
  - RCurl
  - DBI
  - bit
  - bit64
  - prettyunits
  - blob
  - RSQLite